
export const icons = {
    play: require("./icons/play.png"),
    share: require("./icons/share.png"),
    qrCode: require("./icons/qr-code.png"),
    cart:require("./icons/cart.png"),
    key: require("./icons/key.png"),
    back: require("./icons/back.png"),
    vibrate: require("./icons/vibrate.png"),
    camera: require("./icons/camera.png"),
    clock: require("./icons/clock.png"),
    fullScreen: require("./icons/fullscreen.png"),
    mic: require("./icons/voice-recording.png"),
    lock: require("./icons/lock.png"),
    chat: require("./icons/chat.png"),
    plus: require("./icons/plus.png"),
    menu: require("./icons/menu.png"),
    eyeOpen: require("./icons/eyeOpen.png"),
    eyeClose: require("./icons/eyeClose.png"),
};